<?php

/**
 * @file
 * Contains movie_content.module.
 */

function movie_content_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  // We will identify which views to alter based on their ids.
  $id = $variables['view']->id();
  // List of all views that should use the movie-grid layout.
  $grids = ['frontpage', 'movies_grid'];

  if (in_array($id, $grids) || (strpos($id, "feature_") === 0)) {
    $suggestions[] = sprintf('views_view__movie_grid', $variables['view']->id());
  }
}
